# Buildpacks to include in builder
[[buildpacks]]
id = "dev.kameshs.cnbs.java-11"
image = "docker://quay.io/kameshsampath/java-11-jvm-bp:{{VERSION}}"

[[buildpacks]]
id = "dev.kameshs.cnbs.maven-settings"
image = "docker://quay.io/kameshsampath/maven-settings-bp:{{VERSION}}"


[[order]]
    # Configure Maven Settings
    [[order.group]]
    id = "dev.kameshs.cnbs.maven-settings"
    version = "0.0.1"
    
    # Configure Maven Settings
    [[order.group]]
    id = "dev.kameshs.cnbs.java-11"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "dev.kameshs.cnbs.stacks.java-11"
# This image is used at build-time
build-image = "quay.io/kameshsampath/cnbs-build:java-11-{{VERSION}}"
# This image is used at runtime
run-image = "quay.io/kameshsampath/cnbs-run:java-11-{{VERSION}}"