# Buildpack API version
api = "0.4"

# Buildpack ID and metadata
[buildpack]
id = "dev.kameshs.java.maven"
version = "0.0.1"
name = "Java Maven Buildpack"

[[stacks]]
id = "dev.kameshs.stacks.java-11"
build-image = "quay.io/kameshsampath/cnbs-java-11-build"
run-image   = "quay.io/kameshsampath/cnbs-java-11-run"