# Buildpacks to include in builder
[[buildpacks]]
id = "dev.kameshs.cnbs.quarkus-native"
image = "docker://quay.io/kameshsampath/quarkus-native-bp:{{VERSION}}"

[[order]]
    # Quarkus Native 
    [[order.group]]
    id = "dev.kameshs.cnbs.quarkus-native"

# Stack that will be used by the builder
[stack]
    id = "dev.kameshs.cnbs.stacks.quarkus-native"
    # This image is used at build-time
    build-image = "quay.io/kameshsampath/cnbs-build:quarkus-native-{{VERSION}}"
    # This image is used at runtime
    run-image = "quay.io/kameshsampath/cnbs-run:quarkus-native-{{VERSION}}"