# Buildpack API version
api = "0.4"

# Buildpack ID and metadata
[buildpack]
id = "dev.kameshs.cnbs.quarkus-native"
version = "0.0.1"
name = "Quarkus Native Mode Buildpack(Maven)"

[[stacks]]
id = "dev.kameshs.cnbs.stacks.quarkus-native"
