# Buildpack API version
api = "0.4"

# Buildpack ID and metadata
[buildpack]
id = "dev.kameshs.cnbs.java-11"
version = "0.0.1"
name = "Java 11 Buildpack(Maven)"

[[stacks]]
id = "dev.kameshs.cnbs.stacks.java-11"